name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * *'

jobs:
  dl:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12', '3.11', '3.10', '3.9']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install lxml
    - name: Run dl
      run: |
        python dl.py
    - name: Run datel
      run: |
        python datel.py
